from __future__ import annotations

import json
import os
from datetime import UTC, datetime
from pathlib import Path

from openclaw_watchdog import detect_executor_runtime
from openclaw_watchdog import detect_service_runtime


def now_iso() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def extract_json(text: str) -> dict[str, object] | None:
    text = text.strip()
    if not text:
        return None
    decoder = json.JSONDecoder()
    for index, char in enumerate(text):
        if char != "{":
            continue
        try:
            payload, _ = decoder.raw_decode(text[index:])
        except json.JSONDecodeError:
            continue
        if isinstance(payload, dict):
            return payload
    return None


def run_json(engine, command: list[str], *, timeout: int = 20) -> dict[str, object] | None:
    result = engine.run_command(command, timeout=timeout)
    return extract_json(result.output)


def path_probe(path: Path) -> dict[str, object]:
    existing = path
    while not existing.exists() and existing.parent != existing:
        existing = existing.parent
    return {
        "path": str(path),
        "exists": path.exists(),
        "writable": os.access(path if path.exists() else existing, os.W_OK),
        "existing_anchor": str(existing),
    }


def render_suggested_env(payload: dict[str, object]) -> str:
    suggestions = payload.get("suggested_env", {})
    if not isinstance(suggestions, dict):
        suggestions = {}
    lines = [
        "# Suggested config generated by `openclaw-watchdog detect`",
        "# Review carefully before promoting to a live deployment config.",
        "",
    ]
    sections = [
        (
            "Required / confirm-first",
            [
                "OPENCLAW_CONFIG",
                "OPENCLAW_GATEWAY_SERVICE",
                "OPENCLAW_GATEWAY_PORT",
                "WATCHDOG_PRIMARY_CONVERSATION_TARGETS",
            ],
        ),
        (
            "Recommended defaults",
            [
                "WATCHDOG_STATE_DIR",
                "WATCHDOG_LOG_FILE",
                "WATCHDOG_INCIDENTS_DIR",
                "WATCHDOG_ENABLE_SERVICE_LEVEL_PROBE",
                "WATCHDOG_ENABLE_CONVERSATION_PROBE",
            ],
        ),
        (
            "Safer first rollout",
            [
                "WATCHDOG_ENABLE_DOCTOR_REPAIR",
                "WATCHDOG_ENABLE_SURVIVABILITY_FLOW",
                "WATCHDOG_ENABLE_SURVIVAL_MODE",
            ],
        ),
    ]
    for title, keys in sections:
        lines.append(f"# {title}")
        for key in keys:
            if key not in suggestions:
                continue
            lines.append(f'{key}="{suggestions[key]}"')
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_suggested_env(payload: dict[str, object], target: Path) -> Path:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_suggested_env(payload), encoding="utf-8")
    return target


def detect_payload(engine) -> dict[str, object]:
    commands = detect_executor_runtime.detect_commands()
    executors = detect_executor_runtime.executor_inventory(engine, commands)
    openclaw_command = commands.get("openclaw", {}) if isinstance(commands.get("openclaw"), dict) else {}
    openclaw_available = bool(openclaw_command.get("available"))
    timeout_seconds = int(engine.config.watchdog_service_level_timeout_seconds)
    status_payload = (
        run_json(
            engine,
            ["openclaw", "status", "--json", "--timeout", str(timeout_seconds * 1000)],
            timeout=timeout_seconds + 5,
        )
        if openclaw_available
        else None
    )
    health_payload = (
        run_json(engine, ["openclaw", "health", "--json"], timeout=timeout_seconds + 5)
        if openclaw_available
        else None
    )
    gateway = detect_service_runtime.gateway_probe(engine, status_payload)
    channels = detect_service_runtime.channel_probe(health_payload)
    openclaw_config_probe = {
        "path": str(engine.config.openclaw_config),
        "exists": engine.config.openclaw_config.exists(),
    }
    env_file = engine.config.env_file
    conversation = status_payload.get("conversation") if isinstance(status_payload, dict) else {}
    conversation = conversation if isinstance(conversation, dict) else {}
    channel_summary = status_payload.get("channelSummary") if isinstance(status_payload, dict) else []
    channel_summary = channel_summary if isinstance(channel_summary, list) else []
    suggested_env = {
        "OPENCLAW_CONFIG": str(engine.config.openclaw_config),
        "OPENCLAW_GATEWAY_SERVICE": engine.config.openclaw_gateway_service,
        "OPENCLAW_GATEWAY_PORT": str(gateway.get("detected_port", engine.config.openclaw_gateway_port)),
        "WATCHDOG_STATE_DIR": str(engine.config.watchdog_state_dir),
        "WATCHDOG_LOG_FILE": str(engine.config.watchdog_log_file),
        "WATCHDOG_INCIDENTS_DIR": str(engine.config.watchdog_incidents_dir),
        "WATCHDOG_PRIMARY_CONVERSATION_TARGETS": ",".join(channels["suggested_primary_targets"]),
        "WATCHDOG_ENABLE_SERVICE_LEVEL_PROBE": str(bool(engine.config.watchdog_enable_service_level_probe)).lower(),
        "WATCHDOG_ENABLE_CONVERSATION_PROBE": str(bool(engine.config.watchdog_enable_conversation_probe)).lower(),
        "WATCHDOG_ENABLE_DOCTOR_REPAIR": "false",
        "WATCHDOG_ENABLE_SURVIVABILITY_FLOW": "false",
        "WATCHDOG_ENABLE_SURVIVAL_MODE": "false",
    }
    return {
        "detected_at": now_iso(),
        "repo_root": str(engine.config.repo_root),
        "env_file": str(env_file) if env_file else "",
        "commands": commands,
        "executors": executors,
        "openclaw": {
            "installed": openclaw_available,
            "config": openclaw_config_probe,
            "status_available": status_payload is not None,
            "health_available": health_payload is not None,
        },
        "gateway": gateway,
        "state_dir": path_probe(engine.config.watchdog_state_dir),
        "log_file_parent": path_probe(engine.config.watchdog_log_file.parent),
        "channels": channels,
        "status_summary": {
            "conversation_status": str(conversation.get("status", "") or ""),
            "channel_summary": channel_summary,
        },
        "suggested_env": suggested_env,
    }


def print_detect(payload: dict[str, object]) -> None:
    commands = payload.get("commands", {}) if isinstance(payload.get("commands"), dict) else {}
    executors = payload.get("executors", {}) if isinstance(payload.get("executors"), dict) else {}
    gateway = payload.get("gateway", {}) if isinstance(payload.get("gateway"), dict) else {}
    channels = payload.get("channels", {}) if isinstance(payload.get("channels"), dict) else {}
    state_dir = payload.get("state_dir", {}) if isinstance(payload.get("state_dir"), dict) else {}
    openclaw = payload.get("openclaw", {}) if isinstance(payload.get("openclaw"), dict) else {}

    print(f"detected_at={payload.get('detected_at', '')}")
    print(f"repo_root={payload.get('repo_root', '')}")
    print(f"env_file={payload.get('env_file', '') or 'none'}")
    print(f"openclaw_installed={str(bool(openclaw.get('installed', False))).lower()}")
    config_probe = openclaw.get("config", {}) if isinstance(openclaw.get("config"), dict) else {}
    print(f"openclaw_config={config_probe.get('path', '') or 'none'}")
    print(f"openclaw_config_exists={str(bool(config_probe.get('exists', False))).lower()}")
    print(f"gateway_service={gateway.get('service', '') or 'none'}")
    print(f"gateway_service_active={str(bool(gateway.get('service_active', False))).lower()}")
    print(f"gateway_port={gateway.get('detected_port', gateway.get('configured_port', 0))}")
    print(f"gateway_reachable={str(bool(gateway.get('reachable', False))).lower()}")
    print(f"gateway_url={gateway.get('url', '') or 'none'}")
    print(f"state_dir={state_dir.get('path', '') or 'none'}")
    print(f"state_dir_exists={str(bool(state_dir.get('exists', False))).lower()}")
    print(f"state_dir_writable={str(bool(state_dir.get('writable', False))).lower()}")
    configured = channels.get("configured", []) if isinstance(channels.get("configured"), list) else []
    active = channels.get("active", []) if isinstance(channels.get("active"), list) else []
    print(f"channels_configured={','.join(configured) if configured else 'none'}")
    print(f"channels_active={','.join(active) if active else 'none'}")
    suggested = channels.get("suggested_primary_targets", []) if isinstance(channels.get("suggested_primary_targets"), list) else []
    print(f"suggested_primary_targets={','.join(suggested) if suggested else 'gateway'}")
    available = [name for name, info in commands.items() if isinstance(info, dict) and info.get("available")]
    missing = [name for name, info in commands.items() if isinstance(info, dict) and not info.get("available")]
    rescue_available = [name for name, info in executors.items() if isinstance(info, dict) and info.get("available")]
    rescue_missing = [name for name, info in executors.items() if isinstance(info, dict) and not info.get("available")]
    print(f"commands_available={','.join(available) if available else 'none'}")
    print(f"commands_missing={','.join(missing) if missing else 'none'}")
    print(f"rescue_executors_available={','.join(rescue_available) if rescue_available else 'none'}")
    print(f"rescue_executors_missing={','.join(rescue_missing) if rescue_missing else 'none'}")
    print("next_step=review suggested_env and run preflight once implemented")
